# Generated by Django 4.2.7 on 2023-12-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
