# Generated by Django 4.2.7 on 2023-12-03 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('first', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
